"""user

Revision ID: 3c20b1c4a432
Revises: 9e6bca02671c
Create Date: 2024-10-17 17:19:27.427408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c20b1c4a432'
down_revision: Union[str, None] = '9e6bca02671c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
